---
# tasks file for fab.debsources
    - name: Copie source list
      become: yes
      copy:
        src: sourcesliste.debian.9
        dest: /etc/apt/sources.list
        backup: yes
        owner: root
        group: root
        mode: 0644
      when: (ansible_distribution|lower == "debian" and ansible_distribution_major_version == "9")

