---
galaxy_info:
    author: conn
    description: ntp client configuration
    license: BSD 3-Clause License
    min_ansible_version: 2.2

    platforms:
        - name: Debian

          versions:
              - stretch

    galaxy_tags:
        - system
