---
# tasks file for fl.sshkey
# 
  - name: Efface ancien authorized_keys
    become: yes
    become_user: "{{ ssh_user }}"
    command: cp ~/.ssh/authorized_keys ~/.ssh/authorized_keys.old
    when: (sshkey_clean == True )

  - name : remplace la clef
    become: yes
    become_user: "{{ ssh_user }}"
    copy:
      src: "authorized_keys.{{ ssh_user }}"
      dest: ~/.ssh/authorized_keys
      mode: 0600
    when: (sshkey_clean == True )

  - name: check user path
    become: yes
    shell: >
            egrep "^{{ ssh_user }}:" /etc/passwd | awk -F: '{ print $6 }'
    changed_when: false
    register: userhome 
    when: (sshkey_clean != True )

  - name: debug path
    become: yes
    debug:
      msg: "{{ userhome.stdout }}"
    when: (sshkey_clean != True )

  - name: Ajoute la clef dans le fichier
    become: yes
    vars:
      keyssh: "{{ lookup('file', 'authorized_keys.{{ ssh_user }}' ) }}"
    blockinfile:
      create: yes
      backup: yes
      path: "{{ userhome.stdout}}/.ssh/authorized_keys"
      block: "{{ keyssh }}"
    when: (sshkey_clean != True )

