---
# tasks file for fl.ntp

  - import_tasks: install_ntp_packages.yml
    when: (ansible_os_family|lower == "debian")
  - import_tasks: set_ntp_date.yml
    when: ansible_os_family|lower == 'debian'
