---
# tasks
    - name: install  package debian
      environment:
        http_proxy: http://192.168.4.60:3128/
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - ntp
        - ntpdate
        - python
        - python-simplejson
        - apt-transport-https
        - software-properties-common
