---
- hosts: all
sudo: yes
roles:
  - { role: "fl.ntp" }
  - { role: "fl.debupdate" }
  - { role: "fl.sshkey" }
  - { role: "fab.debupdate" }
  - { role: "fab.debsources" }
  - { role: "fab.debcommon" }
  - { role: "fab.confntp" }

